routes/web.php
<?php

use App\Events\MessageSent;
use App\Http\Controllers\PapeisController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\NotificacaoController;
use App\Models\Notificacao;
use App\Models\User;
use App\Services\MailtrapService;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Laravel\Jetstream\Http\Controllers\Inertia\UserProfileController;

Route::get('/', [MainController::class, 'main'])->name('main');


Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'main'])->name('dashboard');

    /* Rotas do Chat Pusher */
    Route::get('/chat', [NotificacaoController::class, 'index'])->name('chat');
    Route::post('/chat-autenticar-users', [NotificacaoController::class, 'autenticar'])->name('chat.auth');
    Route::post('/chat/send-message', [NotificacaoController::class, 'sendMessage'])->name("chat.send");
    Route::get('/chat/messages/{usuario_destinatario_id}', [NotificacaoController::class, 'fetchMessages']);
    Route::post('/notificacao/ler/{usuarioQueEstaConversando}', [NotificacaoController::class, 'marcarNotificacoesComoLidas']);

    // Rotas para o chat mobile
    Route::get('/chat-mobile', [NotificacaoController::class, 'mobileChat'])->name('chat.mobile');
    Route::post('/chat-mobile/autenticar-users', [NotificacaoController::class, 'autenticar'])->name('chat.mobile.auth');
    Route::post('/chat-mobile/send-message', [NotificacaoController::class, 'sendMessage'])->name("chat.mobile.send");
    Route::get('/chat-mobile/messages/{usuario_destinatario_id}', [NotificacaoController::class, 'fetchMessages']);


    /* Rotas do Email */
    Route::get('/email', [MailController::class, 'main'])->name('email');
    Route::post('/email/send-email', [MailController::class, 'index'])->name('emailSend');
    Route::post('/upload-image', [MailController::class, 'uploadImage'])->name('uploadImage');
    Route::get('/inbox', [MailController::class, 'listEmails'])->name('inbox');
    Route::get('/inbox/{inboxId}/{messageId}', [MailController::class, 'showEmail'])->name('showEmail');
});

/* Rotas que so Admin pode acessar */
Route::middleware(['admin'])->group(function () {
    Route::resource('users', UsersController::class);
    Route::get('/usuarios/list', [UsersController::class, 'list'])->name('users.list');
    Route::resource('papeis', PapeisController::class);
    // Route::get('/search', [UsersController::class, 'search'])->name('users.search');
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Auth;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'papel_id',
        'profile_photo_path',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array<int, string>
     */
    protected $appends = [
        'profile_photo_url',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    public function isAdmin(){
        if (Auth::check()) {
            $user = Auth::user();
            if ($user->papel->nome == "Admin") {
                return true;
            }
        }
        return false;
    }
    

    public function logs(): HasMany
    {
        return $this->hasMany(Log::class);
    }

    public function canal_habilitados(): HasMany
    {
        return $this->hasMany(Canal_habilitado::class);
    }

    public function notificacaos(): HasMany
    {
        return $this->hasMany(notificacao::class);
    }
    

    public function papel(): BelongsTo
    {
        return $this->belongsTo(Papel::class);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\Papel;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\Facades\DataTables;

class UsersController extends Controller
{

    public readonly User $user;

    public function __construct()
    {
        $this->user = new User();
    }

    public function index(Request $request)
    {
        $users = $this->user->with('papel');

        if ($request->ajax()) {
            return DataTables::of($users)
                ->addColumn('profile_photo', function ($user) {
                    return asset('storage/' . $user->profile_photo_path);
                })
                ->addColumn('actions', function ($user) {
                    return view('admin.user.actions', compact('user'));
                })
                ->rawColumns(['profile_photo', 'actions'])
                ->make(true);
        }

        return view('admin.user.users');
    }



    public function create()
    {
        $papels = Papel::all();
        return view('admin.user.users_create', ['papels' => $papels]);
    }

    public function store(Request $request)
    {
        $nomecompleto = $request->input('nome') . ' ' . $request->input('sobrenome');

        if (!$this->user->where('name', $nomecompleto)->exists()) {
            $papelid = $request->input('papel_id');
            $data = 'profile-photos/profilePhotoDefault.png';

            if ($request->hasFile('profile_photo')) {
                $imageName = time() . '_' . $request->file('profile_photo')->getClientOriginalName();

                try {
                    $request->file('profile_photo')->move(public_path('storage/profile-photos'), $imageName);
                    $data = 'profile-photos/' . $imageName;
                    // dd($data);
                } catch (\Exception $e) {
                    return back()->withErrors(['file_error' => $e->getMessage()]);
                }
            }
            //dd($imageName);
            //dd($data);
            $criarUser = $this->user->create([
                'name' => $nomecompleto,
                'email' => $request->input('email'),
                'password' => Hash::make($request->input('senha')),
                'papel_id' => $papelid,
                'created_at' => now(),
                'updated_at' => now(),
                'profile_photo_path' => $data,
            ]);

            if ($criarUser) {
                return redirect()->route('users.index')->with('success', 'Usuário criado com sucesso');
            } else {
                return redirect()->route('users.index')->with('error', 'Erro ao criar usuário');
            }
        }
    }


    public function show(string $id) {}

    public function edit(string $id)
    {
        $user = $this->user->findOrFail($id);
        $papels = Papel::all();

        return view('admin.user.users_edit', ['user' => $user, 'papels' => $papels]);
    }

    public function update(Request $request, string $id)
    {
        $user = $this->user->findOrFail($id);

        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email|max:255|unique:users,email,' . $id,
            'password' => 'nullable|min:8|confirmed',
            'papel_id' => 'required|exists:papel,id',
            'profile-photo' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
        ]);

        $user->name = $request->input('name');
        $user->email = $request->input('email');
        $user->papel_id = $request->input('papel_id');

        if ($request->filled('password')) {
            $user->password = Hash::make($request->input('password'));
        }

        if ($request->hasFile('profile_photo')) {
            $imageName = time() . '_' . $request->file('profile_photo')->getClientOriginalName();

            $request->file('profile_photo')->move(public_path('storage/profile-photos'), $imageName);

            if ($user->profile_photo_path && file_exists(public_path($user->profile_photo_path))) {
                unlink(public_path($user->profile_photo_path));
            }

            $user->profile_photo_path = 'profile-photos/' . $imageName;
        }

        if ($user->save()) {
            return redirect()->route('users.index')->with('success', 'Usuário atualizado com sucesso!');
        }

        return redirect()->back()->with('error', 'Erro ao atualizar usuário!');
    }

    public function destroy(string $id)
    {
        $user = $this->user->findOrFail($id);

        try {
            $user->delete();
            return redirect()->route('users.index')->with('success', 'Usuário excluído com sucesso');
        } catch (\Exception $e) {
            return redirect()->route('users.index')->with('error', 'Erro ao excluir o usuário');
        }
    }

  
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/admin/user/actions.blade.php
<a class="btn btn-sm btn-primary" href="{{ route('users.edit', $user->id) }}" role="button">Editar</a>
<button type="button" class="btn btn-sm btn-danger" onclick="event.preventDefault(); document.getElementById('delete-user-form-{{ $user->id }}').submit()">
    Deletar
</button>
<form id="delete-user-form-{{ $user->id }}" action="{{ route('users.destroy', $user->id) }}" method="POST" style="display: none;">
    @csrf
    @method('DELETE')
</form>

resources/views/admin/user/users.blade.php
@extends('layouts.main')

@section('title', 'Gerenciar Usuários')

@section('content')
    <style>
        body {
            background-color: #f9f9f9;
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            height: 100vh;
        }

        main {
            display: flex;
            justify-content: center;
            align-items: center;
            width: 100%;
            height: 100%;
        }

        .container {
            background: #ffffff;
            border-radius: 10px;
            padding: 20px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            max-width: 800px;
            width: 100%;
        }

        .page-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }

        .page-header h1 {
            font-size: 1.8rem;
            color: #333;
        }

        .btn-primary a {
            color: #ffffff;
            text-decoration: none;
        }

        .btn-primary a:hover {
            color: #ffffff;
            text-decoration: underline;
        }

        .table {
            width: 100%;
            background-color: #ffffff;
            margin-top: 10px;
            border-collapse: collapse;
        }

        .table thead {
            background-color: #007bff;
            color: #ffffff;
        }

        .table th {
            padding: 10px;
            text-align: left;
            font-size: 1rem;
        }

        .table tbody tr {
            border-bottom: 1px solid #ddd;
        }

        .table tbody tr:hover {
            background-color: #f1f1f1;
        }

        .table td {
            padding: 10px;
            vertical-align: middle;
        }

        .profile-photo {
            width: 50px;
            height: 50px;
            border-radius: 50%;
            object-fit: cover;
            border: 2px solid #ddd;
            display: block;
        }

        .btn-action {
            width: 70px;
            height: 40px;
            padding: 5px;
        }

        select {
            width: 55px;
        }

        #users-table_paginate>span>a {
            border: 2px solid #007bff !important;
            border-radius: 50px !important;
            background-color: #007bffb9 !important;
            color: #000000 !important;
            cursor: pointer !important;
        }

        .dataTables_wrapper .dataTables_paginate .paginate_button .next{
            background-color: #007bff;
            color: #fff;
            border: none;
        }

        .dataTables_wrapper .dataTables_paginate .paginate_button:hover{
            background-color: #007bff !important;
            color: #fff !important;
        }   
    </style>

    <x-app-layout>
        <div class="container lista">
            <div class="page-header">
                <h1>Gerenciar Usuários</h1>
                <button class="btn btn-primary">
                    <a href="{{ route('users.create') }}">Criar Usuário <span><i class="fa-solid fa-user-plus"></i></span></a>
                </button>
            </div>

            <table class="table" id="users-table">
                <thead>
                    <tr>
                        <th scope="col">Perfil</th>
                        <th scope="col">Nome</th>
                        <th scope="col">Email</th>
                        <th scope="col">Opções</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </x-app-layout>
@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            $('#users-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ route('users.index') }}',
                columns: [{
                        data: 'profile_photo_path',
                        name: 'profile_photo_path',
                        render: function(data, type, row) {
                            if (!data) {
                                return '<img src="storage/profile-photos/profilePhotoDefault.png" class="profile-photo" />';
                            }

                            return '<img src="storage/' + data + '" class="profile-photo" />';
                        }
                    },
                    {
                        data: 'name',
                        name: 'name'
                    },
                    {
                        data: 'email',
                        name: 'email'
                    },
                    {
                        data: 'actions',
                        name: 'actions',
                        orderable: false,
                        searchable: true,
                        render: function(data, type, row) {
                            return `<button onclick="window.location.href='/users/${row.id}/edit'" class="btn btn-action btn-primary">Editar</button>
                                    <button type="button" class="btn btn-action btn-danger" onclick="confirmDeletion(${row.id})">Excluir</button>`;
                        }




                    }
                ],

                language: {
                    url: 'https://cdn.datatables.net/plug-ins/1.10.24/i18n/pt_br.json'
                },
                initComplete: function() {
                    const searchInput = $('div.dataTables_filter input');
                    const btnInput = $('paginate_button');

                    searchInput.addClass('form-control');
                    btnInput.removeClass('paginate_button');
                    btnInput.addClass('btn btn-primary form-control');

                    searchInput.attr('placeholder', 'Pesquisar usuários...');

                    searchInput.css({
                        'border': '2px solid #007BFF',
                        'border-radius': '5px',
                        'padding': '5px'
                    });
                }

            });
        });

        function confirmDeletion(userId) {
            Swal.fire({
                title: 'Você tem certeza?',
                text: "Esta ação não pode ser desfeita!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sim, excluir!',
                cancelButtonText: 'Cancelar'
            }).then((result) => {
                if (result.isConfirmed) {
                    const form = document.createElement('form');
                    form.action = `/users/${userId}`;
                    form.method = 'POST';

                    const csrfInput = document.createElement('input');
                    csrfInput.type = 'hidden';
                    csrfInput.name = '_token';
                    csrfInput.value = document.querySelector('meta[name="csrf-token"]').getAttribute('content');

                    const methodInput = document.createElement('input');
                    methodInput.type = 'hidden';
                    methodInput.name = '_method';
                    methodInput.value = 'DELETE';

                    form.appendChild(csrfInput);
                    form.appendChild(methodInput);

                    document.body.appendChild(form);
                    form.submit();
                }
            });
        }
    </script>
@endsection

resources/views/admin/user/users_create.blade.php
@extends('layouts.main')
@section('title', 'Criar Usuário')
@section('content')
    <style>
        .profile-photo-container {
            position: relative;
            width: 100px;
            height: 100px;
            margin: 0 auto;
        }

        .profile-photo {
            width: 100px;
            height: 100px;
            border-radius: 50%;
            object-fit: cover;
            border: 2px solid #055fe5c5;
            display: block;
        }

        .edit-icon {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background-color: rgba(0, 0, 0, 0.44);
            color: white;
            border-radius: 50%;
            padding: 10px;
            cursor: pointer;
            font-size: 18px;
            display: none;
            width: 100px;
            height: 100px;
        }

        .profile-photo-container:hover .edit-icon {
            display: block;
        }

        .edit-icon i {
            position: relative;
            margin-top: 42%;
            size: 80px;
        }

        .form-label {
            font-weight: bold;
        }

        #profile_photo {
            display: none;
        }
    </style>

    <x-app-layout>
        <div class="d-flex justify-content-center align-items-center min-h-screen">
            <div class="container-xxl shadow-sm p-4 mb-5 bg-body-secondary rounded">
                <h1 class="text-center fs-4">Criar Usuário</h1>

                <div class="card p-4">
                    <form action="{{ route('users.store') }}" method="POST" enctype="multipart/form-data" id="form">
                        @csrf

                        <div class="mb-3 text-center">
                            <label for="profile_photo" class="form-label">Foto de Perfil</label>
                            <div class="profile-photo-container">
                                <img id="profilePreview" src="{{ asset('img/profilePhotoDefault.png') }}"
                                    class="profile-photo" alt="Foto de Perfil">
                                <label for="profile_photo" class="edit-icon">
                                    <i class="fas fa-pencil-alt"></i>
                                </label>
                                <input type="file" id="profile_photo" name="profile_photo" accept="image/*">
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="nome" class="form-label">Primeiro Nome</label>
                            <input type="text" class="form-control" placeholder="Primeiro nome" name="nome"
                                id="nome" required>
                        </div>

                        <div class="mb-3">
                            <label for="sobrenome" class="form-label">Sobrenome</label>
                            <input type="text" class="form-control" placeholder="Sobrenome" name="sobrenome"
                                id="sobrenome" required>
                        </div>

                        <div class="mb-3">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" class="form-control" name="email" placeholder="Email" id="email"
                                required>
                        </div>

                        <div class="mb-3">
                            <label for="senha" class="form-label">Senha</label>
                            <input type="password" name="senha" class="form-control" placeholder="Senha" id="senha"
                                required>
                        </div>

                        <div class="mb-3">
                            <label class="form-label">Papel do Usuário</label>
                            @foreach ($papels as $papel)
                                <div class="form-check">
                                    <input type="radio" class="form-check-input" id="papel_{{ $papel->id }}"
                                        name="papel_id" value="{{ $papel->id }}" required>
                                    <label for="papel_{{ $papel->id }}"
                                        class="form-check-label">{{ $papel->nome }}</label>
                                </div>
                            @endforeach
                        </div>

                        <div id="errorMessages"></div>

                        <div class="d-flex justify-content-end mt-4">
                            <a href="{{ route('users.index') }}" class="btn btn-secondary me-2">Cancelar</a>
                            <input type="submit" class="btn btn-success" value="Criar">
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <script>
            document.getElementById('profile_photo').addEventListener('change', function(event) {
                const reader = new FileReader();
                reader.onload = function(e) {
                    document.getElementById('profilePreview').src = e.target.result;
                };
                reader.readAsDataURL(event.target.files[0]);
            });
        </script>
    </x-app-layout>
@endsection

resources/views/admin/user/users_edit.blade.php
@extends('layouts.main')
@section('title', 'Editar Usuário')
@section('content')
    <style>
        .profile-photo-container {
            position: relative;
            width: 100px;
            height: 100px;
            margin: 0 auto;
        }

        .profile-photo {
            width: 100px;
            height: 100px;
            border-radius: 50%;
            object-fit: cover;
            border: 2px solid #055fe5c5;
            display: block;
        }

        .edit-icon {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background-color: rgba(0, 0, 0, 0.44);
            color: white;
            border-radius: 50%;
            padding: 10px;
            cursor: pointer;
            font-size: 18px;
            display: none;
            width: 100px;
            height: 100px;
        }

        .profile-photo-container:hover .edit-icon {
            display: block;
        }

        .edit-icon i {
            position: relative;
            margin-top: 42%;
        }

        .form-label {
            font-weight: bold;
        }

        #profile_photo {
            display: none;
        }
    </style>

    <x-app-layout>
        <div class="d-flex justify-content-center align-items-center min-h-screen">
            <div class="container-xxl shadow-sm p-4 mb-5 bg-body-secondary rounded">
                <h1 class="text-center fs-4">Editar Usuário</h1>

                <div class="card p-4">
                    <form action="{{ route('users.update', $user->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        <div class="mb-3 text-center">
                            <label for="profile_photo" class="form-label">Alterar Foto de Perfil</label>
                            <div class="profile-photo-container">
                                <img id="profilePreview" 
                                     src="{{ $user->profile_photo_path ? asset('storage/' . $user->profile_photo_path) : asset('img/profilePhotoDefault.png') }}"
                                     class="profile-photo" alt="Foto de Perfil">
                                <label for="profile_photo" class="edit-icon">
                                    <i class="fas fa-pencil-alt"></i>
                                </label>
                                <input type="file" id="profile_photo" name="profile_photo" accept="image/*">
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="name" class="form-label">Nome</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{ $user->name }}" required>
                        </div>

                        <div class="mb-3">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{ $user->email }}" required>
                        </div>

                        <div class="mb-3">
                            <label class="form-label">Papel do Usuário</label>
                            @foreach($papels as $papel)
                                <div class="form-check">
                                    <input type="radio" class="form-check-input" id="papel_{{ $papel->id }}" name="papel_id" value="{{ $papel->id }}" 
                                           {{ $user->papel_id == $papel->id ? 'checked' : '' }} required>
                                    <label for="papel_{{ $papel->id }}" class="form-check-label">{{ $papel->nome }}</label>
                                </div>
                            @endforeach
                        </div>

                        <div class="d-flex justify-content-end mt-4">
                            <a href="{{ route('users.index') }}" class="btn btn-secondary me-2">Cancelar</a>
                            <button type="submit" class="btn btn-primary">Salvar Alterações</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <script>
            document.getElementById('profile_photo').addEventListener('change', function(event) {
                const reader = new FileReader();
                reader.onload = function(e) {
                    document.getElementById('profilePreview').src = e.target.result;
                };
                reader.readAsDataURL(event.target.files[0]);
            });
        </script>
    </x-app-layout>
@endsection